Feature Engineering/Preprocessing

Mean and Variance

In [1]:
import numpy as np

# Example 1xN vector
N = 5
vector = np.array([2, 4, 6, 8, 10])
print("Vector:", vector)

# Compute mean
mean = np.mean(vector)
print("Mean:", mean)

# Compute sample variance
variance = np.var(vector, ddof=1)  # ddof=1 for sample variance
print("Variance (Sample):", variance)


Vector: [ 2  4  6  8 10]
Mean: 6.0
Variance (Sample): 10.0


Covariance between two vectors represents.

In [2]:
import numpy as np

# Example 1xM vectors
M = 5
vector1 = np.array([2, 4, 6, 8, 10])
vector2 = np.array([1, 3, 5, 7, 9])

# Compute covariance
covariance = np.cov(vector1, vector2)[0, 1]  # Covariance between vector1 and vector2
print("Covariance between vector1 and vector2:", covariance)


Covariance between vector1 and vector2: 10.0


Correlation

In [3]:
import numpy as np

# Example 1xN vectors
N = 5
vector1 = np.array([2, 4, 6, 8, 10])
vector2 = np.array([1, 3, 5, 7, 9])

# Compute correlation
correlation = np.corrcoef(vector1, vector2)[0, 1]  # Correlation between vector1 and vector2
print("Correlation between vector1 and vector2:", correlation)


Correlation between vector1 and vector2: 0.9999999999999999


covariance matrix and correlation matrix.

In [4]:
import numpy as np

# Example MxN feature matrix
M = 3
N = 5

# Random MxN feature matrix
X = np.random.rand(M, N)
print("Feature Matrix X:\n", X)

# Compute the covariance matrix
cov_matrix = np.cov(X)
print("\nCovariance Matrix:\n", cov_matrix)

# Compute the correlation matrix
corr_matrix = np.corrcoef(X)
print("\nCorrelation Matrix:\n", corr_matrix)


Feature Matrix X:
 [[0.82055461 0.17999327 0.01194362 0.52421881 0.84494251]
 [0.65207649 0.12996478 0.36966848 0.32349679 0.20820048]
 [0.3953103  0.75837232 0.26585004 0.20445155 0.21273186]]

Covariance Matrix:
 [[ 0.14003232  0.02662866 -0.03097741]
 [ 0.02662866  0.03999379 -0.01333681]
 [-0.03097741 -0.01333681  0.05360629]]

Correlation Matrix:
 [[ 1.          0.35582707 -0.35753875]
 [ 0.35582707  1.         -0.28803661]
 [-0.35753875 -0.28803661  1.        ]]
